repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        exclude: ^.idea/
      - id: end-of-file-fixer
        exclude: ^.idea/
      - id: check-yaml
        exclude: ^.idea/
      - id: debug-statements
        exclude: ^.idea/
      - id: requirements-txt-fixer
        exclude: ^.idea/

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.2
    hooks:
      - id: ruff-format
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, --config=ruff.toml]
        types_or: [python, pyi]
        require_serial: true
