repos:
  # Custom terminal komutu
  - repo: local
    hooks:
      - id: remove-pycache
        name: Remove __pycache__ folders
        entry: find . -type d -name "__pycache__" -exec rm -r {} +
        language: system
        pass_filenames: false
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        exclude: ^.idea/
      - id: end-of-file-fixer
        exclude: ^.idea/
      - id: check-yaml
        exclude: ^.idea/
      - id: debug-statements
        exclude: ^.idea/
      - id: requirements-txt-fixer
        exclude: ^.idea/
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.2
    hooks:
      # Önce linting işlemi yaparak importları düzenleyin ve kullanılmayan importları tespit edin
      - id: ruff
        args:
          [--fix, --exit-non-zero-on-fix, --config=ruff.toml, --select=I, F401]
        types_or: [python, pyi]
        require_serial: true
      # Sonra formatlamayı yapın
      - id: ruff-format
        types_or: [python, pyi]
