repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: debug-statements
      - id: requirements-txt-fixer
  # - repo: https://github.com/PyCQA/isort
  #   rev: v5.12.0
  #   hooks:
  #     - id: isort
  #       args: [
  #          '--rm', 'from __future__ import annotations',        # 3.7-3.11
  #          '--rm', 'from __future__ import absolute_import',  # -3.0
  #          '--rm', 'from __future__ import division',         # -3.0
  #          '--rm', 'from __future__ import generator_stop',   # -3.7
  #          '--rm', 'from __future__ import generators',       # -2.3
  #          '--rm', 'from __future__ import nested_scopes',    # -2.2
  #          '--rm', 'from __future__ import print_function',   # -3.0
  #          '--rm', 'from __future__ import unicode_literals', # -3.0
  #          '--rm', 'from __future__ import with_statement',   # -2.6
  #         ]
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v3.1.0
    hooks:
      - id: add-trailing-comma
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: ["-j8", "--ignore=E701,E203,W503,E501", "--exclude=.git,__pycache__,venv"]
